### ISSUE TITLE
Parallelise `SPLIT_BY_RANK` across multiple processes

### ISSUE THREAD

**Issue by jackscanlan** [AVR-biosecurity-bioinformatics/mimir#50]
At the moment `SPLIT_BY_RANK` splits an input `.fasta` into multiple `.fasta` (one per shared taxonomic lineage down to a given rank) using `grep` and a single CPU. This time-scales poorly for realistic database sizes when the rank is species or genus, so needs a rework. 

Alternative implementation could be a step to split the input `.fasta` into smaller chunks (40k?), run them into `SPLIT_BY_RANK` in parallel, then recombine the files with matching names (probably in a dedicated process).

**Comment by alexpiper** [comment]
I think this could be done more efficiently with awk, rather than looped grep i.e. https://stackoverflow.com/questions/53343938/most-efficient-method-to-split-file-into-multiple-files-based-on-a-column
